---
title: "calibration"
basedOn: "default.yaml"
# scope and resolution
periods: [2000, 2005, 2010, 2015, 2020]
startyear: 2005
calibperiods: 2005
regionmapping: ["regionmappingEU27asOne.csv", "mredgebuildings"]
regions: EUR
ltFactor: 1.5
ltEternalShare: 0.15
ignoreShell: TRUE
reportingTemplate: ignoreShell_onlyRes
# switches
switches:
  RUNTYPE: calibration
  CALIBRATIONMETHOD: logit
# parameters for calibration
calibrationParameters:
  stepSizeInit: 80
  iterations: 3
  iterationsArmijo: 10
...
